### ISSUE TITLE
Exception Class Naming Semantics 

### ISSUE THREAD

**Issue by harkinwebb** [AyeAyeApi/Api#31]
Current Exception and \Exception is a little confusing to read 

try{
  //Blah
} catch (Exception $e) {
	//Blah	
} catch (\Exception $e) {
	//Blah
}
​
This might read better

try{
	//Blah
} catch (AyeAyeException $e) {
	//Blah	
} catch (\Exception $e) {
	//Blah
}
`

If I then do this 
​
class IansApiBuiltOnAyeAyeException extends AyeAyeException{}
​
//It reads nicely where the exception has been thrown from 
try{
	//Blah
} catch (IansApiBuiltOnAyeAyeException $e) {
	//Blah	
}
} catch (AyeAyeException $e) {
	//Blah	
} catch (\Exception $e) {
	//Blah
}

**Comment by Gisleburt** [comment]
I agree, but it's too late to change the class name (for version 1) because it would be BC breaking. What you can do however is this:

```php
use AyeAye\Api\Exception as AyeAyeException;

...
try{
    //Blah
} catch (AyeAyeException $e) {
    //Blah
} catch (\Exception $e) {
    //Blah
}
```

If you like, you can submit a PR where this is changed in https://github.com/AyeAyeApi/Api/blob/8e18310a9fe13dd936a4f9b44f192ba37a3a2782/src/Api.php#L12-L19 which will make it more obvious to people who are just reading through.

(If you don't fancy it, let me know and I'll update it myself, just wanted to give you first dibs :wink:)
